grpc_options:
  port: 9000
  grpc_servicer_functions:
    - ray_pb2_grpc.add_UserDefinedServiceServicer_to_server
    - ray_pb2_grpc.add_ImageClassificationServiceServicer_to_server

applications:
  - name: app1
    route_prefix: /app1
    import_path: RayDeployment:app
    runtime_env: {}